[pytest]
#python_files = test_*.py
#python_classes = Test*
#python_function = test_*
#addopts = -ra -q
markers =
    regression: Маркировка для регрессионных тестов.
    registration: Маркировка для тестов, связанных с регистрацией пользователей.
    authorization: Маркировка для тестов, связанных с авторизацией пользователей.
